name: "yolo_base64"
platform: "ensemble"
max_batch_size: 8

input [
  {
    name: "IMAGE_BASE64"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "BBOXS"
    data_type: TYPE_STRING
    dims: [1]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "preprocess"
      model_version: -1
      input_map: {
        key: "images_base64"
        value: "IMAGE_BASE64"
      }
      output_map: {
        key: "images"
        value: "IMAGES"
      }
      output_map: {
        key: "shapes"
        value: "SHAPES"
      }
    },
    {
      model_name: "yolov8"
      model_version: -1
      input_map: {
        key: "input__0"
        value: "IMAGES"
      }
      output_map: {
        key: "output__0"
        value: "YOLO_OUTPUT"
      }
    },
    {
      model_name: "postprocess"
      model_version: -1
      input_map: {
        key: "model_answer"
        value: "YOLO_OUTPUT"
      }
      input_map: {
        key: "shapes"
        value: "SHAPES"
      }
      output_map: {
        key: "output_json"
        value: "BBOXS"
      }
    }
  ]
}